"""add_table_t_request_to_admin_status

Revision ID: 0bb6dc1c27f9
Revises: dac59ba3a0a2
Create Date: 2025-04-19 16:15:29.129725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0bb6dc1c27f9'
down_revision: Union[str, None] = 'dac59ba3a0a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_request_to_admin_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_request_to_admin_status',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_user', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['t_users.id'], name='t_request_to_admin_status_id_user_fkey'),
    sa.PrimaryKeyConstraint('id', name='t_request_to_admin_status_pkey')
    )
    # ### end Alembic commands ###
