"""add_table_t_request_to_admin_status

Revision ID: 12afd762e20c
Revises: 0bb6dc1c27f9
Create Date: 2025-04-19 16:15:49.050230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12afd762e20c'
down_revision: Union[str, None] = '0bb6dc1c27f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
