"""add_images

Revision ID: 413ff7a2c1ac
Revises: 8d71bf2294de
Create Date: 2025-02-27 10:55:10.674890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '413ff7a2c1ac'
down_revision: Union[str, None] = '8d71bf2294de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_yoga_poses_images',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('id_pose', sa.BigInteger(), nullable=False),
    sa.Column('image', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['id_pose'], ['t_yoga_poses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_yoga_poses_images')
    # ### end Alembic commands ###
