"""add_images

Revision ID: 4ed4e73bb647
Revises: a58fea04b9e1
Create Date: 2025-02-27 11:03:36.082635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ed4e73bb647'
down_revision: Union[str, None] = 'a58fea04b9e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_yoga_poses_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_pose', sa.BigInteger(), nullable=False),
    sa.Column('image', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['id_pose'], ['t_yoga_poses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_yoga_poses_images')
    # ### end Alembic commands ###
