"""add_column_russian_translate

Revision ID: 51befcbd1914
Revises: 5e30d6ad0186
Create Date: 2025-04-18 13:03:12.908688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51befcbd1914'
down_revision: Union[str, None] = '5e30d6ad0186'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_result_predictions', sa.Column('right_answer_russian_interpretation', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_result_predictions', 'right_answer_russian_interpretation')
    # ### end Alembic commands ###
