"""delete_column_russian_translate

Revision ID: 5e30d6ad0186
Revises: 7457e635727e
Create Date: 2025-04-18 13:02:48.682628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e30d6ad0186'
down_revision: Union[str, None] = '7457e635727e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_result_predictions', 'title_russian_interpretation')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_result_predictions', sa.Column('title_russian_interpretation', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
