"""add_field_russian

Revision ID: 6000f91f287f
Revises: 4ed4e73bb647
Create Date: 2025-03-11 17:07:37.480651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6000f91f287f'
down_revision: Union[str, None] = '4ed4e73bb647'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_yoga_poses', sa.Column('title_russian_interpretation', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_yoga_poses', 'title_russian_interpretation')
    # ### end Alembic commands ###
