"""add_field_verify_user

Revision ID: 6795fb447e26
Revises: acf41fee3167
Create Date: 2025-02-01 12:21:59.206051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6795fb447e26'
down_revision: Union[str, None] = 'acf41fee3167'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_users', sa.Column('is_verify', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_users', 'is_verify')
    # ### end Alembic commands ###
