"""user_permission_study_add

Revision ID: 6b0d4c925a69
Revises: 70e3968b9e86
Create Date: 2024-11-26 16:39:21.986590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b0d4c925a69'
down_revision: Union[str, None] = '70e3968b9e86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_users', sa.Column('permission_study', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_users', 'permission_study')
    # ### end Alembic commands ###
