"""create_table_yoga_pose

Revision ID: 6e0ecb439549
Revises: 6b0d4c925a69
Create Date: 2024-11-26 17:53:58.910950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e0ecb439549'
down_revision: Union[str, None] = '6b0d4c925a69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_yoga_poses',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('title_sanskrit', sa.String(length=256), nullable=False),
    sa.Column('title_transliteration', sa.String(length=256), nullable=False),
    sa.Column('title_russian', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_yoga_poses')
    # ### end Alembic commands ###
