"""user_is_admin_add

Revision ID: 70e3968b9e86
Revises: bd26996d3ff2
Create Date: 2024-11-26 15:57:41.850771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70e3968b9e86'
down_revision: Union[str, None] = 'bd26996d3ff2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_users', sa.Column('is_admin', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_users', 'is_admin')
    # ### end Alembic commands ###
