"""add_column_russian_translate

Revision ID: 7457e635727e
Revises: 6000f91f287f
Create Date: 2025-04-18 13:01:35.664150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7457e635727e'
down_revision: Union[str, None] = '6000f91f287f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_result_predictions', sa.Column('title_russian_interpretation', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_result_predictions', 'title_russian_interpretation')
    # ### end Alembic commands ###
