"""add_column_reports

Revision ID: 8d71bf2294de
Revises: c60fd58d1500
Create Date: 2025-02-08 12:03:10.544494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d71bf2294de'
down_revision: Union[str, None] = 'c60fd58d1500'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_reports', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_reports', 'created_at')
    # ### end Alembic commands ###
