"""add_field_mail_user

Revision ID: 9a725ae1a84b
Revises: 6795fb447e26
Create Date: 2025-02-01 12:33:37.050667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a725ae1a84b'
down_revision: Union[str, None] = '6795fb447e26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_users', sa.Column('mail', sa.String(length=256), nullable=False))
    op.create_unique_constraint(None, 't_users', ['mail'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 't_users', type_='unique')
    op.drop_column('t_users', 'mail')
    # ### end Alembic commands ###
