"""add_table_t_request_to_admin_status

Revision ID: 9eac3ff10621
Revises: 51befcbd1914
Create Date: 2025-04-19 16:08:45.790867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9eac3ff10621'
down_revision: Union[str, None] = '51befcbd1914'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_request_to_admin_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_user', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['t_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_request_to_admin_status')
    # ### end Alembic commands ###
