"""add_images

Revision ID: a58fea04b9e1
Revises: 413ff7a2c1ac
Create Date: 2025-02-27 11:03:22.345933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a58fea04b9e1'
down_revision: Union[str, None] = '413ff7a2c1ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_yoga_poses_images')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_yoga_poses_images',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_pose', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('image', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_pose'], ['t_yoga_poses.id'], name='t_yoga_poses_images_id_pose_fkey'),
    sa.PrimaryKeyConstraint('id', name='t_yoga_poses_images_pkey')
    )
    # ### end Alembic commands ###
