"""add_table_t_request_to_admin_status

Revision ID: dac59ba3a0a2
Revises: 9eac3ff10621
Create Date: 2025-04-19 16:14:45.967809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dac59ba3a0a2'
down_revision: Union[str, None] = '9eac3ff10621'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
